automation_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('news_searcher',include(('news_searcher.urls', "news_searcher"), namespace= 'news')),
    path('', include(('gantt_chart.urls', "gantt_chart"), namespace= 'gantt_chart')),
]

gantt_chart/urls.py
from django.contrib import admin
from django.urls import path

from .views import *



urlpatterns = [
    path('', gantt_chart_index, name = 'gantt_chart_index'),
    path("get_data", fetchJsonData, name="fetchJsonData"),

]

gantt_chart/models.py
from django.db import models

# Create your models here.

gantt_chart/views.py
from django.shortcuts import render, HttpResponse, redirect
from django.template import loader
from django.http import JsonResponse
from django.urls import reverse
from gantt_chart.lib.gantt_chart_lib import *



def gantt_chart_index(request):
    return render(request, 'gantt_chart/gantt_chart_index.html')



def fetchJsonData(request):
    manager = GanttChartManager( pd.Timestamp.now() - pd.Timedelta(days=1), pd.Timestamp.now())
    manager.get_data()
    data = manager.get_json_of_data()

    return JsonResponse({"Status": "OK", "data": data})

gantt_chart/templates/gantt_chart/gantt_chart_index.html
<html>
    <head>
        <script src="https://cdn.plot.ly/plotly-3.0.1.min.js" charset="utf-8"></script>
        <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    </head>
    <body>
        <div id="root">




        </div>  
        
        
<script>
    $(document).ready(function(){
        fetchJsonData();
    });

    function fetchJsonData() {
        $.ajax({
            url: "{% url 'gantt_chart:fetchJsonData' %}",
            type: 'GET',
            dataType: 'json',
            success: function(data) {
                console.log('JSON Data:', data);
                plot_gantt_chart(data['data']);
                // Process the JSON data here
            },
            error: function(xhr, status, error) {
                console.error('Error fetching data:', error);
            }
        });
    }

    function plot_gantt_chart(data) {
        data = JSON.parse(data);
    
        // Assign a unique numerical value to each toolID
        let toolMap = {};
        let uniqueTools = [...new Set(data.map(d => d.toolID))];
        uniqueTools.forEach((tool, index) => {
            toolMap[tool] = index + 1; // Assign numerical y value
        });
    
        let statusColors = {
            "UP": "green",
            "LOST": "blue",
            "WEQ": "pink",
            "TPE": "purple"
        };
    
        // Create traces for bars
        let traces = data.map(d => ({
            x: [d.StartTime, d.EndTime], // Start and End times
            y: [toolMap[d.toolID], toolMap[d.toolID]], // Use numeric y-axis
            mode: "lines+markers",
            marker: { size: 1, color: statusColors[d.Status] || "gray" },
            line: { width: 30, color: statusColors[d.Status] || "gray" },
            name: d.Status,
            hoverinfo: "x+y+name"
        }));
    
        // Create annotation-like text traces
        let textTraces = data
            .filter(d => d.Remark) // Only include items with remarks
            .map(d => ({
                x: [(new Date(d.EndTime)).getTime()], // Position text at EndTime
                y: [toolMap[d.toolID] + 0.1], // Shift text slightly above the bar
                mode: "text",
                text: [d.Remark],
                textposition: "top center",
                textfont: { size: 12, color: "black" },
                showlegend: false
            }));
    
        let layout = {
            title: "Tool Usage Timeline",
            xaxis: { title: "Time", type: "date" },
            yaxis: {
                title: "Tool ID",
                tickvals: Object.values(toolMap), // Use numeric y values
                ticktext: Object.keys(toolMap),   // Show original tool names
                categoryorder: "array",
                categoryarray: Object.keys(toolMap).reverse()
            },
            showlegend: false // Hide the legend
        };
    
        Plotly.newPlot('root', [...traces, ...textTraces], layout).then(function (gd) {
            gd.on('plotly_click', function (data) {
                console.log(data.points[0]);
            });
        });
    }

</script>


    </body>


</html>