automation_project/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('news_searcher',include(('news_searcher.urls', "news_searcher"), namespace= 'news')),
    path('', include(('gantt_chart.urls', "gantt_chart"), namespace= 'gantt_chart')),
]

gantt_chart/urls.py
from django.contrib import admin
from django.urls import path

from .views import *



urlpatterns = [
    path('', gantt_chart_index, name = 'gantt_chart_index'),
    path("get_data", fetchJsonData, name="fetchJsonData"),

]

news_searcher/urls.py
from django.contrib import admin
from django.urls import path

from .views import *



urlpatterns = [
    path('', views_email_group.mail_gorup_index, name = 'mail_group_index'),
    path('mail_group_delete', views_email_group.mail_group_delete, name = 'mail_group_delete'),
    path('mail_group_add_keyword', views_email_group.mail_group_add_keyword, name = 'mail_group_add_keyword'),
    path('mail_group_delete_keyword', views_email_group.mail_group_delete_keyword, name = 'mail_group_delete_keyword'),


    path('keyword_management', views_keyword_management.keyword_management_index, name = 'keyword_management_index'),
    path('keyword_management_edit/<int:id>', views_keyword_management.keyword_management_edit, name = 'keyword_management_edit'),
    path('keyword_management_delete', views_keyword_management.keyword_management_delete, name = 'keyword_management_delete'),


    path('exclusion_site_management', views_exclusion_site_management.exclusion_site_management_index, name = 'exclusion_site_management_index'),
    path('exclusion_site_management_delete', views_exclusion_site_management.exclusion_site_management_delete, name = 'exclusion_site_management_delete'),
]

news_searcher/models.py
import configparser
from django.db import models
from loguru import logger
from django.conf import settings
import os



class KeywordRecord(models.Model):
    keyword = models.TextField(blank=True)  # String for search or crawling purposes
    correlation_words = models.TextField(blank=True)
    description = models.TextField(blank=True)  # Optional description of the group


class NewsRecord(models.Model):
    title = models.CharField(max_length=300)  # Title of the news record
    link = models.URLField()  # URL link to the full news article
    source = models.CharField(max_length=255)  # Source name or website of the article
    file_location = models.TextField(blank=True, null=True)  # Path to the file (optional)
    doi_id = models.CharField(max_length=255, blank=True, null=True)
    affiliation = models.TextField(blank=True, null=True)
    date = models.DateTimeField(blank=True, null=True)



class CorrelationRecord(models.Model):
    news_record = models.ForeignKey(NewsRecord, on_delete=models.CASCADE)
    keyword_record = models.ForeignKey(KeywordRecord, on_delete=models.CASCADE)


class MailGroup(models.Model):
    name = models.CharField(max_length=255)  # The name of the subscription group
    email_list = models.TextField(default="[]")  # A list of email addresses, stored as a text
    main_group = models.CharField(max_length=15, blank=True, null=True)
    level = models.IntegerField(default=1)

    def get_email_list(self):
        return eval(self.email_list)

    def get_config_file(self):
        email_group_folder = os.path.join(settings.MAIL_GROUP_CONFIG_FOLDER, self.name)
        os.makedirs(email_group_folder, exist_ok=True)
        return os.path.join(email_group_folder, f"{self.name}.ini")

    def syn_from_config_file(self):
        config_file = self.get_config_file()
        if not os.path.exists(config_file):
            logger.debug("No config file found, creating with default settings")
            self.create_config_file(config_file)
        else:
            config = configparser.ConfigParser()
            config.read(config_file)
            email_list = config.get("MailGroup", "email_list")
            level = config.getint("MailGroup", "level")

            self.email_list = email_list
            self.level = int(level)
            self.save()

    def create_config_file(self, config_file):
        config = configparser.ConfigParser()
        config.add_section("MailGroup")
        config.set("MailGroup", "name", self.name)
        config.set("MailGroup", "email_list", "[]")
        config.set("MailGroup", "level", "1")
        with open(config_file, "w") as f:
            config.write(f)


class KeywordRecordSubscription(models.Model):
    keyword = models.ForeignKey(KeywordRecord, on_delete=models.CASCADE, null=True)
    mail_group = models.ForeignKey(MailGroup, on_delete=models.CASCADE, null=True)


class ExclusionSiteRecord(models.Model):
    site = models.CharField(max_length=255)

    def __str__(self):
        return self.site
    


class NewsSendRecord(models.Model):
    mail_group_name = models.CharField(max_length=255, null=True)
    news_record = models.ForeignKey(NewsRecord, on_delete=models.CASCADE, null=True)
    timestamp = models.DateTimeField(null = True)

news_searcher/forms.py
from django import forms
from .models import *
import os
from django.core.exceptions import ValidationError









class KeywordRecordForm(forms.ModelForm):
    class Meta:
        model = KeywordRecord
        fields = ['keyword', 'correlation_words', 'description']

        # chnge the field class as form-control
        widgets = {
            'keyword': forms.TextInput(attrs={'class': 'form-control'}),
            'correlation_words': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
        }

class MailGroupForm(forms.ModelForm):
    class Meta:
        model = MailGroup
        fields = ['name', 'level']

        # chnge the field class as form-control
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'mails': forms.Textarea(attrs={'class': 'form-control', 'rows': 3}),
            'level': forms.NumberInput(attrs={'class': 'form-control', 'type': 'number', 'min': '1', 'max': '3', 'value': '3'}),
        }



class ExclusionSiteRecordForm(forms.ModelForm):
    class Meta:
        model = ExclusionSiteRecord
        fields = ['site']

        # chnge the field class as form-control
        widgets = {
            'site': forms.TextInput(attrs={'class': 'form-control'}),
        }

news_searcher/views/views_email_group.py
from django.shortcuts import render, HttpResponse, redirect
from django.template import loader
from django.http import JsonResponse

from news_searcher.models import *
from news_searcher.forms import *
from news_searcher.lib.news_search_lib import MailGroupManager
from django.urls import reverse


def mail_group_delete(request):
    mail_group_id = request.POST.get('id')
    mail_group = MailGroup.objects.get(id=mail_group_id)
    mail_group.delete()
    return redirect(reverse('news:mail_group_index'))


def mail_gorup_index(request):
    records = MailGroup.objects.all().order_by("name")
    keyword_records = KeywordRecord.objects.all().order_by("keyword")

    for mail_group in records:
        subscription_records = KeywordRecordSubscription.objects.filter(mail_group=mail_group)
        keyword_list = [subscription.keyword.keyword for subscription in subscription_records]
        mail_group.keyword_list = keyword_list
        mail_group.syn_from_config_file()


    form = MailGroupForm()
    if request.method == 'POST':
        if MailGroup.objects.filter(name=request.POST['name']).exists():
            return redirect(reverse('news:mail_group_index'))
        form = MailGroupForm(request.POST)
        if form.is_valid():
            new_mail_group = form.save()
            new_mail_group.syn_from_config_file()


            return redirect(reverse('news:mail_group_index'))
    cotext = {"records": records, "keyword_records": keyword_records, "form": form}
    return render(request, 'news_searcher/mail_group/mail_group_index.html', cotext)



def mail_group_add_keyword(request):
    mail_group_id = request.POST.get('id')
    keyword_id = request.POST.get('keyword_id')
    subscription_record, created = KeywordRecordSubscription.objects.get_or_create(keyword_id=keyword_id, mail_group_id=mail_group_id)
    subscription_record.save()

    mail_group = MailGroup.objects.get(id=mail_group_id)
    subscription_records = KeywordRecordSubscription.objects.filter(mail_group=mail_group)
    keyword_list = [subscription.keyword.keyword for subscription in subscription_records]
    return JsonResponse({"keyword_list": keyword_list})



def mail_group_delete_keyword(request):
    mail_group_id = request.POST.get('mail_group_id')
    keyword = request.POST.get('keyword')

    subscription_record = KeywordRecordSubscription.objects.get(mail_group_id=mail_group_id, keyword__keyword=keyword)
    subscription_record.delete()

    mail_group = MailGroup.objects.get(id=mail_group_id)
    subscription_records = KeywordRecordSubscription.objects.filter(mail_group=mail_group)
    keyword_list = [subscription.keyword.keyword for subscription in subscription_records]
    return JsonResponse({"keyword_list": keyword_list})

news_searcher/views/views_exclusion_site_management.py
from django.shortcuts import render, HttpResponse, redirect
from django.template import loader
from django.http import JsonResponse

from news_searcher.models import *
from news_searcher.forms import *
from django.urls import reverse

def exclusion_site_management_index(request):
    records = ExclusionSiteRecord.objects.all().order_by("site")

    form = ExclusionSiteRecordForm()
    if request.method == 'POST':
        if ExclusionSiteRecord.objects.filter(site=request.POST['site']).exists():
            return redirect(reverse('news:exclusion_site_management_index'))
        form = ExclusionSiteRecordForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('news:exclusion_site_management_index'))

    return render(request, 'news_searcher/exclusion_site_management/exclusion_site_management_index.html', {"records": records, "form": form})


def exclusion_site_management_delete(request):
    id = request.POST.get('id')
    record = ExclusionSiteRecord.objects.get(id=id)
    record.delete()

    return JsonResponse({"Status": "Success"})

news_searcher/views/views_keyword_management.py
from django.shortcuts import render, HttpResponse, redirect
from django.template import loader
from django.http import JsonResponse
from news_searcher.models import *
from news_searcher.forms import *
from django.urls import reverse


def keyword_management_index(request):
    records = KeywordRecord.objects.all().order_by("keyword")

    form = KeywordRecordForm()
    if request.method == 'POST':
        if KeywordRecord.objects.filter(keyword=request.POST['keyword']).exists():
            return redirect(reverse('news:keyword_management_index'))
        form = KeywordRecordForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect(reverse('news:keyword_management_index'))

    return render(request, 'news_searcher/keyword_management/keyword_management_index.html', {"records": records, "form": form})


def keyword_management_edit(request, id):
    record=  KeywordRecord.objects.get(id=id)

    form = KeywordRecordForm(request.POST or None, instance=record)

    if request.method == 'POST':
        if form.is_valid():
            form.save()
            return redirect(reverse('news:keyword_management_index'))

    return render(request, 'news_searcher/keyword_management/keyword_management_edit.html', {"form": form})


def keyword_management_delete(request):
    id = request.POST.get('id')
    record = KeywordRecord.objects.get(id=id)
    record.delete()

    return JsonResponse({"Status": "Success"})

news_searcher/templates/news_searcher/keyword_management/keyword_management_edit.html
{% extends "news_searcher/base.html" %}

{% block content %}

<body>  
    <h3>Keyword Record Edit</h3>
    <form method="POST" class="post-form" enctype="multipart/form-data">  
        <div class="form-group">
            <table class="table table-bordered table-hover" style="width: 80%;">
                <tbody>
                    {% csrf_token %}  
                    {{ form.as_table }}
                    <tr>
                        <td colspan="2"><button type="submit" class="btn btn-outline-primary">Save</button>  </td>
                    </tr>
                
                </tbody>
            </table>

        </div>
    </form>  
</body>  

{% endblock %}

{% block script %}

{% endblock %}

news_searcher/templates/news_searcher/keyword_management/keyword_management_index.html
{% extends "news_searcher/base.html" %}
{% load static %}

{% block head %}


{% endblock %}


{% block content %}
<h2>Keyword Management</h2>


<h3>New Keyword Record</h3>

<form method="POST" class="post-form" enctype="multipart/form-data">  
    <div class="form-group">
        <table class="table table-bordered table-hover" style="width: 80%;">
            <tbody>
                {% csrf_token %}  
                {{ form.as_table }}
                <tr>
                    <td colspan="2"><button type="submit" class="btn btn-outline-primary">Save</button>  </td>
                </tr>
            
            </tbody>
        </table>

    </div>
</form>

<h3>Keyword Records</h3>
<table class="table table-bordered table-hover" style="width: 80%;" id="keyword_table">
    <thead>
        <tr>
            <th>Keyword</th>
            <th>Description</th>
            <th>Correlation Question</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        {% for keyword_record in records %}
            <tr>
                <td style="font-weight: bold;">{{keyword_record.keyword}}</td>
                <td>{{keyword_record.description}}</td>
                <td>{{keyword_record.correlation_words}}</td>
                <td>
                    <a href="{% url 'news:keyword_management_edit' keyword_record.id %}" class="btn btn-outline-primary">Edit</a>
                    <button onclick="keyword_management_delete('{{keyword_record.id}}')" class="btn btn-outline-danger">Delete</button>
                </td>
            </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}


{% block script %}
{% load static %}

<script>
    $(document).ready( function () {
        $('#keyword_table').DataTable();
    })

    function keyword_management_delete(id) {
        $.ajax({
            url: "{% url 'news:keyword_management_delete' %}",
            type: "POST",
            headers: { "X-CSRFToken": csrftoken }, // Correct way to pass CSRF token
            data: {
                id: id,
            },
            success: function (data) {
                location.reload();
            }
        });
    }

</script>
{% endblock %}